### ISSUE TITLE
No such file or directory: 'smalisca/data/config/config.conf'

### ISSUE THREAD

**Issue by alexzaitsev** [dorneanu/smalisca#12]
Hello, I'm running smalisca on the linux mint. I can't analyze my sqlite:

```
$ smalisca analyzer -f sqlite -i base.sqlite 
                            ___                                   
                           /\_ \    __                            
  ____    ___ ___      __  \//\ \  /\_\    ____    ___     __     
 /',__\ /' __` __`\  /'__`\  \ \ \ \/\ \  /',__\  /'___\ /'__`\   
/\__, `\/\ \/\ \/\ \/\ \L\.\_ \_\ \_\ \ \/\__, `\/\ \__//\ \L\.\_ 
\/\____/\ \_\ \_\ \_\ \__/.\_\/\____\\ \_\/\____/\ \____\ \__/.\_\
 \/___/  \/_/\/_/\/_/\/__/\/_/\/____/ \/_/\/___/  \/____/\/__/\/_/



--------------------------------------------------------------------------------
:: Author:   Victor <Cyneox> Dorneanu
:: Desc:     Static Code Analysis tool for Smali files
:: URL:      http://nullsecurity.net, http://{blog,www}.dornea.nu
:: Version:  0.2
--------------------------------------------------------------------------------

:: INFO       Using default conf (smalisca/data/config/config.conf)
Traceback (most recent call last):
  File "/usr/local/bin/smalisca", line 70, in <module>
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python2.7/dist-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/usr/local/lib/python2.7/dist-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/usr/local/lib/python2.7/dist-packages/smalisca/controller/controller_analyzer.py", line 99, in default
    config.smalisca_conf.read(config.PROJECT_CONF)
  File "/usr/local/lib/python2.7/dist-packages/smalisca/core/smalisca_config.py", line 251, in read
    with codecs.open(filename, 'r', encoding='utf-8') as f:
  File "/usr/lib/python2.7/codecs.py", line 878, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'smalisca/data/config/config.conf'

```

**Comment by chushu10** [comment]
Same problem as yours. Wondering if creating a "config.conf" by yourself is appropriate? e.g: Use the "--config" option

**Comment by dorneanu** [comment]
You can definitely specify a config file:

```
$ smalisca analyzer --help | grep "CONFIG_FILE"
  --config CONFIG_FILE  Specify config file
```

But I agree with you guys, that this is definitely a bug. I'll push some changes ASAP. 

Thanks for your patience.
