### ISSUE TITLE
Encounters: ImportError: No module named configparser

### ISSUE THREAD

**Issue by demonkit** [dorneanu/smalisca#7]
When I type `smalisca --help`, smalisca always gives the error output:

```
Traceback (most recent call last):
  File "/home/demonkit/work/envs/smali/bin/smalisca", line 33, in <module>
    import smalisca.core.smalisca_config as config
  File "/home/demonkit/work/envs/smali/local/lib/python2.7/site-packages/smalisca/core/smalisca_config.py", line 37, in <module>
    import configparser
ImportError: No module named configparser
```

my python env is python 2.7.6, os is ubuntu 14.04.3
want to know how to fix it.
thanks

**Comment by demonkit** [comment]
fixed it by:`pip install configparser`.
I'm a little confused why python 2.7 not containing the package.
