### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dinasaif** [dorneanu/smalisca#9]
Thanks for your help 
I download smalisca but when I write 
$ smalisca --help
This error appear 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\python27\lib\multiprocessing\forking.py", line 503, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named smalisca
Traceback (most recent call last):
  File "C:/Python27/Scripts/smalisca", line 35, in <module>
    from smalisca.controller.controller_parser import ParserController
  File "C:\python27\lib\site-packages\smalisca\controller\controller_parser.py", line 77, in <module>
    class ConcurrentParser():
  File "C:\python27\lib\site-packages\smalisca\controller\controller_parser.py", line 90, in ConcurrentParser
    multimanager = multiprocessing.Manager()
  File "C:\python27\lib\multiprocessing__init__.py", line 99, in Manager
    m.start()
  File "C:\python27\lib\multiprocessing\managers.py", line 528, in start
    self._address = reader.recv()
EOFError
What should I do to solve this error

**Comment by dorneanu** [comment]
You'll have to install it system-wide or using some virtualenv. The "binary" in `bin/smalisca` needs the python module `smalisca` to be installed. Make sure you follow the installation instructions exactly.
